# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
#import os
#import sys
#sys.path.insert(0, os.path.abspath('.'))
#sys.path.insert(0, os.path.abspath('..'))


# -- Project information -----------------------------------------------------
project = 'IRIS Documentation'
copyright = '2020, mobigen'
author = 'mobigen'

# The full version, including alpha/beta/rc tags
release = '1.8.0'

# -- General configuration ---------------------------------------------------

# The master toctree document.
#master_doc = 'docs/index'

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = 'static/common/logo.png'
html_logo = 'user_manual/_static/img/iris-logo.svg'

html_last_updated_fmt = '%b %d, %Y %H:%M'


# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'rst2pdf.pdfbuilder',
    'recommonmark',
    'sphinx_sitemap'
]

pdf_documents = [('index', u'rst2pdf', u'Sample rst2pdf doc', u'Your NAme'), ]
#html_baseurl = 'https://my-site.com/docs/'
html_baseurl = 'https://docs.iris.tools/'

# Global variables available to all templates
html_context = {

    # Enable google analytics
    #'googleanalytics_id': 'UA-67846571-2',
    #'googleanalytics_enabled': True,

    # Enable the "Edit in GitHub link within the header of each page.
    'display_github': True,

    # Set the following variables to generate the resulting github URL for each page.
    # Format Template: https://{{ github_host|default("github.com") }}/{{ github_user }}/{{ github_repo }}/blob/{{ github_version }}{{ conf_py_path }}{{ pagename }}{{ suffix }}
    'github_user': 'mobigen',
    'github_repo': 'docs',
    'github_version': 'master/source/',

    'css_files': []
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']
templates_path = ['templates']

#html_additional_pages = {
    #'index': 'index.html'
#}
# If false, no index is generated.
html_use_index = True

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
#language = 'ko'
language = 'ko'
locale_dirs = ['locale/']
#gettext_compact = True
gettext_compact = False

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
html_theme = 'sphinx_rtd_theme'
#html_style = '/css/theme.css'
html_style = '/css/qgis_docs.css'
#html_style = '/templates/theme.css'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static', 'theme.css']
